---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: atuin-pg-cluster
spec:
  backup:
    target: primary
  bootstrap:
    initdb:
      database: atuin
      dataChecksums: true
      owner: atuin
      postInitApplicationSQL:
        - ALTER USER atuin SET search_path TO "$user", data, public
  env:
    - name: TZ
      value: America/Los_Angeles
  imageName: ghcr.io/cloudnative-pg/postgresql:17@sha256:dab846a58e8ca3c8872584ab2225ee93fb9e659a87c52e163fefae9275b46f51
  instances: 3
  managed:
    services:
      disabledDefaultServices:
        - r
        - ro
  monitoring:
    tls:
      enabled: true
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: garage-objectstore
  postgresql:
    synchronous:
      failoverQuorum: true
      method: any
      number: 1
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: application-infra
  storage:
    size: 10Gi
    storageClass: cnpg-data-encrypted-storage
  walStorage:
    size: 4Gi
    storageClass: cnpg-wal-encrypted-storage
