---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/name: garage
  name: garage-metrics
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 3903
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/name: garage
  type: ClusterIP
