---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/name: garage
  name: garage
spec:
  ports:
    - name: s3-api
      port: 3900
      protocol: TCP
      targetPort: s3-api
    - name: s3-web
      port: 3902
      protocol: TCP
      targetPort: s3-web
  selector:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/name: garage
  type: ClusterIP
