---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/tandoor
  - ../../../components/cnpg-backup
images:
  - name: vabene1111/recipes
    newTag: 2.5.0@sha256:afaa257176f9d64733d27793e557ab680bf381ecef2d207b1a14033a2e4ace0e
namespace: tandoor
patches:
  - path: patches/tandoor/set_config_env.yml
    target:
      kind: StatefulSet
      name: tandoor-statefulset
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
