---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/tandoor
  - ../../../components/cnpg-backup
images:
  - name: vabene1111/recipes
    newTag: 2.5.1@sha256:b3ec4aa3fb9e4d24c73876b79576fca04aa026a6706fe3d5a17d95297bda39b8
namespace: tandoor
patches:
  - path: patches/tandoor/set_config_env.yml
    target:
      kind: StatefulSet
      name: tandoor-statefulset
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
