---
apiVersion: v1
kind: Service
metadata:
  name: tandoor-svc
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: tandoor-web
  selector:
    app.kubernetes.io/name: tandoor
