---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tandoor-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tandoor
  serviceName: tandoor-svc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tandoor
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TANDOOR_PORT
              value: "8080"
            - name: TZ
              value: America/Los_Angeles
          image: vabene1111/recipes
          name: tandoor
          ports:
            - containerPort: 8080
              name: tandoor-web
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: tandoor-mediafiles
            - mountPath: /opt/recipes/staticfiles
              name: tandoor-staticfiles
            - mountPath: /tmp
              name: tandoor-tmp
      priorityClassName: application
      securityContext:
        fsGroup: 65534
      volumes:
        - emptyDir:
            medium: Memory
          name: tandoor-tmp
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tandoor-mediafiles
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn-encrypted
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tandoor-staticfiles
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn-encrypted
