---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: mbround18/valheim
    newTag: 3.4.1@sha256:4e4c209455150200baa0f2237271bd0d196f9b32ae11130f6129ec1ca5f2fa5d
resources:
  - statefulset.yml
  - service.yml
