---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: mbround18/valheim
    newTag: 3.5.0@sha256:68cf418f39b0174e421ca0f063be38a11f1a4aadb48f3b15e9cc7c7be39111a6
resources:
  - statefulset.yml
  - service.yml
