---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.middlewares: auth-forwardauth-middleware@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: opencloud-ingress
spec:
  rules:
    - host: cloud.tswn.us
      http:
        paths:
          - backend:
              service:
                name: opencloud-svc
                port:
                  name: web
            path: /
            pathType: Prefix
