---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: factorio
  serviceName: factorio-svc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: factorio
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: FSM_AUTOSTART
              value: "true"
            - name: FSM_SECURE
              value: "false"
            - name: FSM_SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: ofsm/ofsm
          name: factorio-server-manager
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 34197
              protocol: UDP
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 250m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /opt/factorio/config
              name: factorio-config
            - mountPath: /opt/factorio/mods
              name: factorio-mods
            - mountPath: /opt/factorio/saves
              name: factorio-saves
            - mountPath: /opt/fsm-data
              name: factorio-server-manager-data
      priorityClassName: application
      securityContext:
        fsGroup: 65536
  volumeClaimTemplates:
    - metadata:
        labels:
          # Use this PVC to configure attached PVs.
          recurring-job.longhorn.io/source: enabled
          # Opt out of the default group.
          recurring-job-group.longhorn.io/default: disabled
          # Opt into the game group.
          recurring-job-group.longhorn.io/game: enabled
        name: factorio-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn-encrypted
    - metadata:
        labels:
          # Use this PVC to configure attached PVs.
          recurring-job.longhorn.io/source: enabled
          # Opt out of the default group.
          recurring-job-group.longhorn.io/default: disabled
          # Opt into the game group.
          recurring-job-group.longhorn.io/game: enabled
        name: factorio-mods
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-unencrypted
    - metadata:
        labels:
          # Use this PVC to configure attached PVs.
          recurring-job.longhorn.io/source: enabled
          # Opt out of the default group.
          recurring-job-group.longhorn.io/default: disabled
          # Opt into the game group.
          recurring-job-group.longhorn.io/game: enabled
        name: factorio-saves
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn-unencrypted
    - metadata:
        labels:
          # Use this PVC to configure attached PVs.
          recurring-job.longhorn.io/source: enabled
          # Opt out of the default group.
          recurring-job-group.longhorn.io/default: disabled
          # Opt into the game group.
          recurring-job-group.longhorn.io/game: enabled
        name: factorio-server-manager-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        storageClassName: longhorn-encrypted
