---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: this-is-ignored-but-is-required
spec:
  template:
    spec:
      initContainers:
        - env:
            - name: ATUIN_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: atuin-pg-cluster-app
            - name: ATUIN_DB_PASSWORD_SECRET_FILE
              value: /postgresql-secrets/password
            - name: ATUIN_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: atuin-pg-cluster-app
                  key: username
            - name: ATUIN_OPEN_REGISTRATION
              value: "false"
          name: generate-config
          volumeMounts:
            - mountPath: /postgresql-secrets
              name: postgresql-secrets
              readOnly: true
        - command:
            - sh
            - -c
            - until pg_isready; do echo "waiting for database ${PGHOST}:${PGPORT}/${PGDATABASE}..."; sleep 10; done;
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: atuin-pg-cluster-app
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: atuin-pg-cluster-app
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: atuin-pg-cluster-app
            - name: PGSSLMODE
              value: require
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: atuin-pg-cluster-app
          image: postgres
          name: wait-for-atuin-pg-is-ready
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: postgresql-secrets
          secret:
            secretName: atuin-pg-cluster-app
