---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-objectstore
spec:
  configuration:
    destinationPath: s3://prod-cnpg-backup/$(namespace)/
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: garage-access-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-access-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  retentionPolicy: 30d