---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-objectstore
spec:
  configuration:
    destinationPath: s3://prod-cnpg-backup/$(namespace)/
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: garage-access-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-access-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
    logLevel: info
    retentionPolicyIntervalSeconds: 1800
  retentionPolicy: 30d