---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: this-is-ignored-but-is-required
spec:
  template:
    spec:
      containers:
        - env:
            - name: SPOOLMAN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: spoolman-pg-cluster-app
                  key: host
            - name: SPOOLMAN_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: spoolman-pg-cluster-app
                  key: dbname
            - name: SPOOLMAN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spoolman-pg-cluster-app
                  key: password
            - name: SPOOLMAN_DB_TYPE
              value: postgres
            - name: SPOOLMAN_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spoolman-pg-cluster-app
                  key: username
          name: spoolman
      initContainers:
        - command:
            - sh
            - -c
            - until pg_isready; do echo "waiting for database ${PGHOST}:${PGPORT}/${PGDATABASE}..."; sleep 10; done;
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: spoolman-pg-cluster-app
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: spoolman-pg-cluster-app
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: spoolman-pg-cluster-app
            - name: PGSSLMODE
              value: require
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: spoolman-pg-cluster-app
          image: postgres
          name: wait-for-spoolman-pg-is-ready
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
