---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: garage-admin-endpointslice
  labels:
    kubernetes.io/service-name: garage-admin-svc
addressType: IPv4
ports:
  - name: web
    protocol: TCP
    port: 30186
endpoints:
  - addresses:
      - 10.10.0.14 # chanttogreen.hogs.tswn.us
    conditions:
      ready: true

