---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: spoolman-pg-cluster
spec:
  backup:
    target: primary
  bootstrap:
    initdb:
      database: spoolman
      dataChecksums: true
      owner: spoolman
      postInitApplicationSQL:
        - ALTER USER spoolman SET search_path TO "$user", data, public
  env:
    - name: TZ
      value: America/Los_Angeles
  imageName: ghcr.io/cloudnative-pg/postgresql:17@sha256:4acc01c2c8a3d9b5953e58998251a9158da34b87a83b9f36c1e1fac1e8e9f55d
  instances: 3
  managed:
    services:
      disabledDefaultServices:
        - r
        - ro
  monitoring:
    tls:
      enabled: true
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: garage-objectstore
  postgresql:
    synchronous:
      failoverQuorum: true
      method: any
      number: 1
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: application-infra
  storage:
    size: 10Gi
    storageClass: cnpg-data-encrypted-storage
  walStorage:
    size: 4Gi
    storageClass: cnpg-wal-encrypted-storage
