---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant-pg-cluster
spec:
  backup:
    target: primary
  bootstrap:
    initdb:
      database: homeassistant
      dataChecksums: true
      owner: homeassistant
      postInitApplicationSQL:
        - ALTER USER homeassistant SET search_path TO "$user", data, public
  env:
    - name: TZ
      value: America/Los_Angeles
  imageName: ghcr.io/cloudnative-pg/postgresql:17@sha256:7e16b46cef57750dccaa68790a0796f58bdcfa26c35775512bb0030452dc2627
  instances: 3
  managed:
    services:
      disabledDefaultServices:
        - r
        - ro
  monitoring:
    tls:
      enabled: true
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: garage-objectstore
  postgresql:
    synchronous:
      failoverQuorum: true
      method: any
      number: 1
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: critical-application-infra
  storage:
    size: 30Gi
    storageClass: cnpg-data-encrypted-storage
  walStorage:
    size: 8Gi
    storageClass: cnpg-wal-encrypted-storage
