---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: homeassistant-pg-ingressroutetcp
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`postgres.homeassistant.hogs.tswn.us`)
      middlewares:
        - name: homeassistant-pg-ip-allowlist-middlewaretcp
      services:
        - name: homeassistant-pg-cluster-rw
          port: postgres
  tls:
    secretName: postgres-homeassistant-hogs-tswn-us-secret
    options:
      name: postgres-tlsoption
