---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nightly-scheduledbackup
spec:
  backupOwnerReference: cluster
  cluster:
    name: grafana-pg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: "0 15 23 * * *"  # At 23:15 every day.
