---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: dxflrs/garage
    newTag: v2.2.0@sha256:45a61ce3f7c9c24fc23d9ed2b09b27ed560ab87b34605d175d5c588f539c24e4
resources:
  - daemonset.yml
  - rbac.yml
  - service/garage-metrics.yml
  - service/garage.yml
  - servicemonitor.yml

