# @codegen-command: ansible-playbook plays/codegen/postgres-logical-backup.yml 
# @generated
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - miniobucket/crowdsec.yml
  - miniobucket/immich.yml
  - miniopolicy/crowdsec.yml
  - miniopolicy/immich.yml
  - miniopolicybinding/crowdsec.yml
  - miniopolicybinding/immich.yml
  - miniouser/crowdsec.yml
  - miniouser/immich.yml
