---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cnpg-encrypted-storage
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/node-publish-secret-name: longhorn
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
  csi.storage.k8s.io/provisioner-secret-name: longhorn
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  dataLocality: strict-local
  diskSelector: nvme
  encrypted: "true"
  fromBackup: ""
  numberOfReplicas: "1"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
