---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: deluan/navidrome
    newTag: 0.60.3@sha256:a5dce8f33304714dd138e870cca0dcab3d937ca236be1a9f2b97da009d1a0048
resources:
  - service.yml
  - statefulset.yml
