---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: deluan/navidrome
    newTag: 0.59.0@sha256:4edc8a1de3e042f30b78a478325839f4395177eb8201c27543dccc0eba674f23
resources:
  - service.yml
  - statefulset.yml
