---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: deluan/navidrome
    newTag: 0.60.2@sha256:1b3f9556fc4f70cb1c2d3995543e734bdc90c762c9c6ee9a7c5f6a9745efbc3e
resources:
  - service.yml
  - statefulset.yml
