---
- action: "accept"
  protocol: "vrrp"
  source:
    group:
      address_group: "PEER-v4"
- description: "Allow conntrack-sync"
  action: "accept"
  protocol: "udp"
  destination:
    port: "3780"
  source:
    group:
      address_group: "PEER-v4"
- description: "Allow dhcp-sync"
  action: "accept"
  protocol: "tcp"
  destination:
    port: "520"
  source:
    group:
      address_group: "PEER-v4"
- description: "Allow ICMP"
  action: "accept"
  protocol: "icmp"
  icmp:
    type_name: any
