---
# The prefix for home folders on this system.
# common__home_prefix: /home/
common__home_prefix: /home/

# Groups to create.  For example:
# common__unix_groups:
#   - name: "ansible"
#     gid: 2000
#     sudo: true
common__unix_groups: []

# Users to create.  For example:
# common__unix_groups:
#   - name: "ansible"
#     gid: 2000
common__unix_users: []
