---
wireguard__address: 10.11.2.36/32
wireguard__privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63623535353139363536376438373064353339343935656234663965636335666238653234323065
          3666356336323735376238636664653536356139616534610a376232323432643739656232616361
          61643939313137343936356339393666396635323033663533313837666335306565643464366361
          3761353132313861330a616139366539383235326266316438303433326138646261313339383862
          61643235373335663162353232613561623934313438316136613435306338623038333534653464
          3937626239323430383862343430643162393866366136643339
wireguard__pubkey: Z8nFFCO9tScvgAJMnkkTm/GRQGRUGe2QuyBQeR7yd0w=
