---
wireguard__address: 10.11.2.37/32
wireguard__privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35373266613832646565356161336433303737663762393466613038323066306534636464616438
          3034303861653632653339666536376130346434353636650a623530343032383865313235333132
          37313465383061326563333866373563333338363063333438373034383232363464346164393338
          6132386137346162630a646136646433326166313966353139393437313536636364656565643939
          61356561383361366533313635356335663831373466653430343935303862646635376637663663
          6662363439336132613239393761333763613866666561326439
wireguard__pubkey: Ft7JzLdn8tBelViKHKxaF2LBqNtZR38sR3rVemGEtTE=

