---
ansible_cron__interval: "daily"

common__ip_addresses:
  - "10.117.0.23/23"
  - "fd36:3eb3:43b0:75::17/64"

zwavejs2mqtt__device_serial: "usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_02add15233e4ea118e44c99b994a5d01-if00-port0"
zwavejs2mqtt__network_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663134626536303339666337383233353864306135643264613838346338636235656465313237
          3935323131356335356334383636373866663035666162660a373635656238393437643633613136
          35646131386363353932666365383239646332663462333439396135383264623538323165396334
          3239353630303439660a663930383834396236306165373061333038306262613539353866306264
          31316661346539383733613033353036653561323030326433666237363232383265353030353566
          3161636638313736333036396666626635653431323964303136
zwavejs2mqtt__s2_unauthenticated: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62366564336436643032386536386539346538653638623030316461353565613337336563393738
          3032313861633361666239316663343463343037663034630a336264373832336234636338313362
          35323965666362316361346239623465616461363462306165616237333135633736376561613330
          3237313531383630380a646233666661313433356233376265626462643462323663316438313630
          62666166656234393963626238396466356365306662366333653635393034353434633661383438
          6338363332303565326639306163393366363833333332303466
zwavejs2mqtt__s2_authenticated: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34363161376433366236303365316137623436613137376131623630646438646535343061636430
          6333326332616239396665656663616438383563316138650a386533646531636233323133336264
          61343033353266356138343238613065363265643965353338313931393937613466666331353761
          6135383865343436380a313365616166323361653530323038303233323937383435323036353263
          33356231653533626235626633373939303136396462663837316266326537383161313437373033
          3964373239666233326262316136386434393066613835626536
zwavejs2mqtt__s2_access_control: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35313862303864623566313363633931396262396462363435383634323435656232326631323864
          6466353632663965346666316330383262333534656263640a333338666535393033626161666335
          63306566316363633432393037623838396236396161396266313666656562343738643661346233
          3439343064656639640a346335356166313139626265326435636438613561346230333335306339
          31376436656438333038393134613866623966633535323163323930353965396665323536333736
          3265633735646464353264646136373436363331616439333230
zwavejs2mqtt__username: "zwavejs"
zwavejs2mqtt__password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35313136343439393636326138623737616632313161663764346663366465646662303664303330
          6539656536373937666539313863633338613838343837330a626232336139313266363431383233
          63346331343132346237353362336262386164613666346663373536663862333464323933613139
          3232376138383236320a646634383130643738366130306461626238616136303331363833336265
          61353963316564336464326163643239303866323539646338383761383863393365
