---
ansible_python_interpreter: "/usr/local/bin/python3.7"
ansible_remote_tmp: "/tmp/ansible"

ansible_cron__inventory_file: "prod-inventory"

common__etc_dir: "/usr/local/etc"
common__ip_addresses:
  - "10.117.0.5/23"
  - "fd36:3eb3:43b0:75::5/64"

mysql_server__databases:
  - name: "ara"
  - name: "homeassistant"
  - name: "zabbix"
    collation: "utf8_bin"
    encoding: "utf8"
mysql_server__users:
  - name: "ara"
    hosts:
      - "10.117.0.30"
      - "fd36:3eb3:43b0:75::1e"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63653535666539373364333935613261373338313862353563653662383137386138316530653736
          3433656433633738396362666665373762326663313533350a616333633136333330396364653662
          38316537613764373862323135346664613833306664343632633836323131306562623637366261
          3962383331346139630a376264393633393936613934303533316162393239393334366632623838
          32373133333937646432306664393434313438613330393764346338636632666135386632336637
          6634393531303931613664653939633933363031643365666665
    priv:
      "ara.*": "ALL"
  - name: "homeassistant"
    hosts:
      - "cortana.hogs.tswn.us"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66623263623135303932386330396266313362333338373964616435386230623062623133383861
          6263333537373862653935623935353831303439663233350a626562653963643939616137623734
          37396563333633386538643062306637636339616532623166666335656561623137656538656236
          6332376361353937380a383666323230396362306363303831346236646530636163323062643339
          64656439666665343466616532633639613466313439666665373839626634333534
    priv:
      "homeassistant.*": "ALL"
  - name: "zabbix"
    hosts:
      - "fd36:3eb3:43b0:a::12" # server.zabbix.hogs.tswn.us
      - "fd36:3eb3:43b0:a:42:aff:fe75:20" # Docker container prefers this.
      - "10.10.0.18" # server.zabbix.hogs.tswn.us
      - "zabbix.hogs.tswn.us"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39613332383262643866643339656463656531316663636136646336653864303433313464666163
          3031623732666435396661323035346531313936363630310a303638653732363761313964666266
          34623237666561346335346635303635343561613038373537653835383035336231623336663564
          3436663931353131610a326337656538663263356164396135613430623636363139303131393662
          31383438663330333139636434313565353931656130643033363837653166393262
    priv:
      "zabbix.*": "ALL"
  - name: "zbx_monitor"
    hosts:
      - "localhost"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35663865303032376539326363353132653566623931373333613166356238663833313630353065
          6539663062623662613833626166326536666362303137320a636366616430633863323133653836
          35343630346337393337643864633266316163306237303335653462393730373862323762383935
          3864396131636661340a393466323432653032363733326635616639373139663361393538653434
          39343036653635333638616236656238333435656666323131626333663031646566
    priv:
      "*.*": "REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW"
mysql_server__root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65333864383863393233626330353332663261373031363435346438613138316333396236613639
          3861393233643362616237326231633532333438313166390a623439386431326166373132663739
          36656238386635613031393362616136656263666135383765656665366132393938393164303335
          6164643438323135370a343766616561376562366234313332383933363934636131623335373362
          34353637373262336633616236343962393964386165363761646332303336383533636536363461
          3337653331356436656164613138303333613438643235383838
