---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: atuin-pg-cluster-podmonitor
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: atuin-pg-cluster
  podMetricsEndpoints:
    - port: metrics
      scheme: https
      tlsConfig:
        ca:
          secret:
            name: atuin-pg-cluster-ca
            key: ca.crt
        serverName: atuin-pg-cluster-rw
