---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/7d2d
images:
  - name: vinanrra/7dtd-server
    newTag: v0.9.3@sha256:75d1193fb2470687ee8748f27482524c170f6cbca110e15f48db8d8ff48f15ca
namespace: 7d2d-relic
patches:
  - path: patches/set_load_balancer.yml
    target:
      kind: Service
      name: seven-days-to-die-svc
resources:
  - namespace.yml
  - ingress.yml
